hugging_face: 
  model : BAAI/bge-base-en-v1.5

chunks:
  chunk_size : 1000
  chunk_overlap : 100

give_llm:
  provider : openai
  model : DeepSeek-V4-Pro
  base_url : https://api.hcnsec.cn/v1 # if you are using third party website 

memory :
  db_path : "./document_rag/memory/memory.db"
  APP_DB_PATH : "./document_rag/memory/api/app.db"
  UPLOAD_DIR : "./document_rag/uploads"
  