hugging_face: 
  model : BAAI/bge-base-en-v1.5

chunks:
  chunk_size : 1000
  chunk_overlap : 100



memory :
  db_path : "./document_rag/memory/memory.db"
  APP_DB_PATH : "./document_rag/memory/api/app.db"
  UPLOAD_DIR : "./document_rag/uploads"
  