hugging_face: 
  model : BAAI/bge-base-en-v1.5

chunks:
  chunk_size : 1000
  chunk_overlap : 100

give_llm:
  provider : openai
  model : gpt-5-mini
  base_url : https://api.bluesminds.com/v1 # if you are using third party website 

memory :
  db_path : "./document_rag/memory/memory.db"
  